# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
