# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkroom', '0002_tag_tag_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
